### ISSUE TITLE
feat: SAMやCDKなどを利用可能に

### ISSUE THREAD

**Issue by suz-lab-hiroyasu** [ambient-lab/ambient-tmpl-infra#30]
## 詳細
- SAMやCDKなどをインストールして利用できるように
- 初期プロジェクトの作成
- eslintやprettierなども充実
- SWAGGERもりようできるように
- ローカル実行もできるように
- DockerInDockerが必要かも
- (LocalStack？)
- Actionsでデプロイ
- 言語はPython

## 期待する動作

_新しい仕様・機能が実装された場合、どのような動作を期待しているかを明示してください。_

## 実装アイデア

_仕様・機能の実装に関するアイデアや提案を共有してください。_

## 関連する情報

_関連するドキュメント、スクリーンショット、または参考情報がある場合、こちらにアップロードまたはリンクを貼ってください。_

**Comment by honma-ambient** [comment]
とりあえず進捗状況

SAM,CDK, localstackをDevContainer上にインストールしてテストコードまでは用意済み

**Comment by suz-lab-hiroyasu** [comment]
@honma-ambient honma-ambient 本イシューは、新しいプロジェクト管理方法のPBIとSBIの状態にして完了

**Comment by honma-ambient** [comment]
@suz-lab-hiroyasu 

https://github.com/orgs/ambient-lab/projects/3/views/4?pane=issue&itemId=41643481
親PBIを作成したのでこっちはクローズします
